@baseUrl = http://localhost:5097

GET {{baseUrl}}/todos/
Accept: application/json

### Hent todo 1

GET {{baseUrl}}/todos/11
Accept: application/json


### Opprett en todo

POST {{baseUrl}}/todos
Content-Type: application/json

{
  "text": "Terje"
}

### Oppdater todo

PUT {{baseUrl}}/todos/1
Content-Type: application/json

{
  "text": "Handle melk og kaffe",
  "isDone": true
}